name: Build and push container image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04-node
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout branch
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Login to Gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/bot/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/toast/bubbles:main
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/toast/bubbles:main
          cache-to: type=inline
