name: Compile test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04-node
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'
          cache-dependency-path: |
            go.mod
            go.sum
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v -trimpath ./