name: Compile test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04-node
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version: '1.21.1'
          cache-dependency-path: |
            go.mod
            go.sum
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v -trimpath ./