name: Compile test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest-node
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: '1.21.1'
          cache-dependency-path: |
            go.mod
            go.sum
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -trimpath ./