name: Deploy to production
on:
  registry_package:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-22.04-node
    steps:
      - name: SSH into Docker Host
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd Bubbles && \
            docker compose pull && \
            docker compose up -d --remove-orphans && \
            docker image prune -f