version: '3.8'
services:
  bot:
    container_name: Bubbles
    image: 'git.toast-server.net/toast/bubbles:main@sha256:d5fa5f1acc1db2fec54026fc31846b640f7b5c9f6a6140f7c6c982680f419370'
    volumes:
      - ../tokens.json:/home/bubbles/tokens.json:ro
    expose:
      - 8080:8080
    restart: unless-stopped
    network_mode: host