version: '3.8'
services:
  bot:
    container_name: Bubbles
    image: 'git.toast-server.net/toast/bubbles:main@sha256:e0c40a1bdd8046cd40870799cddfa4d311a76cc969ba1d5ddc6cde0a6887425c'
    volumes:
      - ../tokens.json:/home/bubbles/tokens.json:ro
    expose:
      - 8080:8080
    restart: unless-stopped
    network_mode: host