version: '3.8'
services:
  bot:
    container_name: Bubbles
    image: 'git.toast-server.net/toast/bubbles:main@sha256:90c7d9c3185b353e9a469e1a0007ab94b2bcbe02758ba269a0f9f35f7f89f240'
    volumes:
      - ../tokens.json:/home/bubbles/tokens.json:ro
    expose:
      - 8080:8080
    restart: unless-stopped
    network_mode: host